# Generated by Django 5.1 on 2025-04-19 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('account_number', models.CharField(default='', max_length=200, null=True)),
                ('account_name', models.CharField(default=' ', max_length=200)),
                ('bank_name', models.CharField(default=' ', max_length=200)),
                ('swift_code', models.CharField(default=' ', max_length=200)),
                ('bitcoin_address', models.CharField(default=' ', max_length=200, null=True)),
                ('ethereum_address', models.CharField(default=' ', max_length=200)),
                ('cashapp_tag', models.CharField(default=' ', max_length=200)),
                ('paypal_email', models.CharField(default=' ', max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('alert', models.CharField(choices=[('sweetAlert', 'click on to show'), ('paid', 'mark as paid')], default='sweetAlert', max_length=24)),
                ('status', models.CharField(choices=[('You need to have a Withdrawal Pin in order to facilitate your withdrawal request. Please contact an agent for help on how to get one.', 'You need to have a Withdrawal Pin in order to facilitate your withdrawal request. Please contact an agent for help on how to get one.')], default='You need to have a Withdrawal Pin in order to facilitate your withdrawal request. Please contact an agent for help on how to get one.', max_length=200, null=True)),
                ('kyc', models.CharField(choices=[('swal-2', 'swal-2'), ('swal-4', 'swal-4')], default='#swal-4', max_length=24)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alert1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('alert', models.CharField(choices=[('sweetAlert', 'click on to show'), ('paid', 'mark as paid')], default='paid', max_length=24)),
                ('status', models.CharField(choices=[('Please upgrade your account, your current investment plan does not support this action, the company will email you shortly or contact customer care for more info', 'Please upgrade your account, your current investment plan does not support this action, the company will email you shortly or contact customer care for more info')], default='Please upgrade your account, your current investment plan does not support this transfer, the company will email you shortly or contact customer care for more info.', max_length=200, null=True)),
                ('kyc', models.CharField(choices=[('swal-2', 'swal-2'), ('swal-4', 'swal-4')], default='#swal-4', max_length=24)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alert2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('alert', models.CharField(choices=[('sweetAlert', 'click on to show'), ('paid', 'mark as paid')], default='sweetAlert', max_length=24)),
                ('status', models.CharField(choices=[('KYC has not been uploaded kindly fill in your details on your kyc data table and contact customer care', 'KYC has not been uploaded kindly fill in your details on your kyc data table and contact customer care')], default='KYC has not been uploaded kindly fill in your details on your kyc data table.', max_length=200, null=True)),
                ('kyc', models.CharField(choices=[('swal-2', 'swal-2'), ('swal-4', 'swal-4')], default='#swal-4', max_length=24)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Banktransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('transaction', models.CharField(blank=True, max_length=250, null=True)),
                ('bank', models.CharField(blank=True, max_length=254, null=True)),
                ('accountnumber', models.CharField(blank=True, max_length=254, null=True)),
                ('gateway', models.CharField(blank=True, max_length=254, null=True)),
                ('swift', models.CharField(blank=True, max_length=254, null=True)),
                ('amount', models.CharField(blank=True, default='$10', max_length=250, null=True)),
                ('charge', models.CharField(blank=True, default='pending', max_length=250, null=True)),
                ('status', models.CharField(blank=True, max_length=250, null=True)),
                ('time', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Banktransfer',
                'verbose_name_plural': 'Banktransfers',
            },
        ),
        migrations.CreateModel(
            name='Bitcoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('transaction', models.CharField(blank=True, max_length=250, null=True)),
                ('wallet', models.CharField(blank=True, max_length=250, null=True)),
                ('gateway', models.CharField(blank=True, max_length=254, null=True)),
                ('amount', models.CharField(blank=True, default='$10', max_length=250, null=True)),
                ('charge', models.CharField(blank=True, default='pending', max_length=250, null=True)),
                ('status', models.CharField(blank=True, max_length=250, null=True)),
                ('time', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitcoin',
                'verbose_name_plural': 'Bitcoins',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('capital_balance', models.CharField(default='0.00', max_length=200)),
                ('usd', models.CharField(default='0.00', max_length=200)),
                ('bonus', models.CharField(default='0.00', max_length=200)),
                ('plan', models.CharField(default='Silver', max_length=200)),
                ('verify', models.CharField(default='Unverified', max_length=200)),
                ('currency', models.CharField(default='$', max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('gender', models.CharField(blank=True, max_length=254, null=True)),
                ('country_code', models.CharField(blank=True, max_length=250, null=True)),
                ('country', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=250, null=True)),
                ('year', models.CharField(blank=True, max_length=250, null=True)),
                ('month', models.CharField(blank=True, max_length=250, null=True)),
                ('day', models.CharField(blank=True, max_length=250, null=True)),
                ('valid_id_front', models.ImageField(blank=True, null=True, upload_to='')),
                ('valid_id_back', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('pin', models.CharField(default='1991', max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='avater.png', null=True, upload_to='')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('Report', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('btc', models.CharField(default='4', max_length=200)),
                ('eth', models.CharField(default='-', max_length=200)),
                ('usdt', models.CharField(default='-', max_length=200)),
                ('usdc', models.CharField(default='-', max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wiretransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('transaction', models.CharField(blank=True, max_length=250, null=True)),
                ('bank', models.CharField(blank=True, max_length=254, null=True)),
                ('accountnumber', models.CharField(blank=True, max_length=254, null=True)),
                ('gateway', models.CharField(blank=True, max_length=254, null=True)),
                ('swift', models.CharField(blank=True, max_length=254, null=True)),
                ('amount', models.CharField(blank=True, default='$10', max_length=250, null=True)),
                ('charge', models.CharField(blank=True, default='pending', max_length=250, null=True)),
                ('status', models.CharField(blank=True, max_length=250, null=True)),
                ('time', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wiretransfer',
                'verbose_name_plural': 'Wiretransfers',
            },
        ),
    ]
